### ISSUE TITLE
Preserve existing behaviors in Django branch

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#274]
This issue is to serve as a checklist, to not miss anything. There can be individual issues for specific features.

The references to existing code are to help find the core logic and any nuances; the point isn't to replicate all the logic, much of which is related to using the database as a queue.

* [ ] Kingfisher config file parsing (`config.py`)
  * Note: I made improvements to very similar code in [Kingfisher Views](https://github.com/open-contracting/kingfisher-views/commits/master/ocdskingfisherviews/config.py), which is 100% tested (better error handling and error messages).
* [ ] Logging config (`app.py`, `ocdskingfisher-process-cli`)
  * See https://docs.djangoproject.com/en/3.0/topics/logging/
* [ ] Sentry integration #149
* CLI
  * ~~`list collections`~~ [add a web UI instead]
  * [ ] load (`new-collection`, `local-load`) #155
  * [ ] endload (`end-collection-store`)
  * [x] addstep (`new-transform-compile-releases`, `new-transform-upgrade-1-0-to-1-1`)
  * [x] addnote (`new-collection-note`)
  * [ ] delete (`delete-collection`)
* [ ] Background tasks #172 #242
  * [ ] Upgrade (`upgrade_1_0_to_1_1.py`: `process_release_row`, `process_record_row`) #67 #26
  * [ ] Compile (`compile_releases.py`: `process_ocid`) #222 #204 #11
  * [ ] Check (`checks.py`: `_check_release_row`, `_check_record_row`) #269
  * [ ] Delete (`database.py`: `*delete*` methods) #180
  * [ ] Calculated fields (`database.py`: `update_collection_cached_columns`)
* [ ] API using django-tastypie (`views_api_v1.py`, `store.py`, `util.py`) #47
  * [ ] `/api/v1/submit/file/` #209 #171 #81
  * [ ] `/api/v1/submit/item/`
  * [ ] `/api/v1/submit/file_errors/`
  * [ ] `/api/v1/submit/end_collection_store/` #122
  * [ ] `/prometheus/metrics` (`prometheus.py`)
* [ ] Web UI #265
* [ ] Standard pipeline (i.e. upgrade then compile; check using 1.1)
  * Unlike the current code, this should be possible to override. The standard pipeline can perhaps just be default checkboxes in the web UI.

**Comment by jpmckinney** [comment]
Documentation pages to carry over (incomplete)

* [ ] [Data model](https://kingfisher-process.readthedocs.io/en/latest/data-model.html): This should instead be a page to explain Collection, File and FileItem at a conceptual level.
